my:
 name: forezp
 age: 12
 number:  ${random.int}
 uuid : ${random.uuid}
 max: ${random.int(10)}
 value: ${random.value}
 greeting: hi,i'm  ${my.name}

spring:
  profiles:
    active: test

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.88.13.201:3306/bizhub
      username: user_bizhub
      password: root1234

  jpa:
    hibernate:
      ddl-auto: update  # 第一次简表create  后面用update
    show-sql: true

server:
  tomcat:
    uri-encoding: UTF-8